### ISSUE TITLE
osx: build error: cannot find ../../libs/openFrameworks/video/ofGstUtils.h

### ISSUE THREAD

**Issue by vdonnefort** [arturoc/ofxGStreamer#5] opened 2014-11-06 18:31 UTC
Here's what I get building ofxGStreamer on OSX Maverick and OF master@9286ce72c02a50350f6a873c11f19f99e2f283ca   

```
openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/config.addons.mk:153: *** cannot find addon source file ../../libs/openFrameworks/video/ofGstUtils.h
```

**Comment by AskBre** [comment] 2016-12-10 01:34
Bumping this up. No issues on Linux, but have struggled the last two days trying to compile it for El Capitan with the exact same error. I've tried several more or less sensible changes to addons_config.mk with no luck, and looked through the config.addons.mk, but there's too much makefilemagic going on there for me to get much out of it. I'm on of 0.9.8. Even a tips on where to look would be appreciated!

**Comment by arturoc** [comment] 2016-12-10 17:13
can you try if this works now? there's a different problem with 0.9.8 and this addon though, so to make it work you'll probably need to use the nightly builds

**Comment by AskBre** [comment] 2016-12-15 17:18
The makefile works great now! Should've thought about $(OF_ROOT)... 

However, the compiler (running make from Terminal) complained about not finding 'stun_debug_enable()' and 'stun_debug_disable()', and after commenting out those (in ofxNiceAgent.cpp from ofxNice) it complained about redeclarations of a lot of libnice-related stuff. I simply deinstalled libnice from my system, and now the problem is that all the libraries in what seems to be ofxNice and ofxXMPP are compiled for 32-bit system while I'm on 64. This is all on of_v20161211_osx_release.

Back in 0.9.8 I managed to compile it before seeing your fix using XCode instead of Make, but then met similar problems with libraries compiled for the wrong architecture. I recompiled and replaced all these for 64bit, and the examples finally compiled and ran, but had issues connecting two instances of examples_audio_video (they saw each other, and received the call, but no video was shown).

Not quite sure what to make of this or where to go from here. What was the issues you mentioned with using this addon and 0.9.8? Should I recompile the libs again? Does this at all relate to ofxGStreamer, or should I take this discussion over at the forums?

**Comment by arturoc** [comment] 2016-12-15 18:34
i think the problems you are seeing are not directly related to this addon but to ofxNice and ofxXMPP, i guess you are using ofxGSTRTP? you should open a new issue there, i think the solution is to recompile the respective libraries as universal binaries with support for 32 and 64bits.

i'm going to close this issue since ofxGStreamer is working now fine

**Closed by arturoc** 2016-12-15 18:34 UTC
